spring:
  application:
    name: TaskManager
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5430/taskmanager
    username: taskmanager
    password: taskmanager
  jackson:
    date-format: dd-MM-yyyy
    deserialization:
      fail-on-unknown-properties: false

  liquibase:
    change-log: classpath:/config/liquibase/master.xml
server:
  port: 8080
application:
  feign:
    documents: http://localhost:8081