version: '2'
services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=taskmanager
      - MINIO_SECRET_KEY=taskmanager
    ports:
      - 8082:9000
    command: server /data